
spring:
  application:
    name: cloud-config-center-dev
  cloud:
    config:
      server:
        git:
          uri:  dev
          search-paths:
            - springcloud-config
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
config:
  info : 123123
